version: "3"
services:
    phusion:
        container_name: phusion-passenger
        restart: "no"
        build: .
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        links:
            - mongo
    mongo:
        container_name: dsslab-mongo
        image: mongo
        restart: "no"
        volumes:
            - ./mongoDB/:/data/db
        ports:
            - "27017:27017"
