version: "3"
services:
    phusion:
        container_name: phusion-passenger
        restart: "no"
        build: .
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        links:
            - mongo
            - lamp
    mongo:
        container_name: dsslab-mongo
        image: mongo
        restart: "no"
        volumes:
            - ./mongoDB/:/data/db
        ports:
            - "27017:27017"
    lamp:
        container_name: lamp
        image: "mattrayner/lamp:latest-1804"
        restart: "no"
        volumes:
            - ./phpapp/:/app
            - ./mysqlDB/:/var/lib/mysql
        ports:
        - "8000:80"